# Generated by Codex on 2026-05-24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="min_stock",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(10000)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MaxValueValidator(10000)],
            ),
        ),
    ]
