# Generated by Codex on 2026-05-24

import django.core.validators
from django.db import migrations, models


def clean_existing_customer_identity_data(apps, schema_editor):
    Customer = apps.get_model("sales", "Customer")

    seen_documents = set()
    seen_emails = set()

    for customer in Customer.objects.order_by("id"):
        update_fields = []
        document_id = (customer.document_id or "").strip()
        email = (customer.email or "").strip().lower()
        phone = (customer.phone or "").strip()

        if not document_id.isdigit() or len(document_id) != 8 or document_id in seen_documents:
            if customer.document_id != "":
                customer.document_id = ""
                update_fields.append("document_id")
        else:
            seen_documents.add(document_id)
            if customer.document_id != document_id:
                customer.document_id = document_id
                update_fields.append("document_id")

        if email and email in seen_emails:
            customer.email = ""
            update_fields.append("email")
        elif email:
            seen_emails.add(email)
            if customer.email != email:
                customer.email = email
                update_fields.append("email")

        if not phone.isdigit() or len(phone) != 9:
            if customer.phone != "":
                customer.phone = ""
                update_fields.append("phone")
        elif customer.phone != phone:
            customer.phone = phone
            update_fields.append("phone")

        if update_fields:
            customer.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_alter_sale_cashier"),
    ]

    operations = [
        migrations.RunPython(clean_existing_customer_identity_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="document_id",
            field=models.CharField(
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El DNI debe tener exactamente 8 digitos numericos.",
                        regex="^\\d{8}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                max_length=9,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El telefono debe tener exactamente 9 digitos numericos.",
                        regex="^\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("document_id", "")),
                fields=("document_id",),
                name="unique_customer_document_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=~models.Q(("email", "")),
                fields=("email",),
                name="unique_customer_email",
            ),
        ),
    ]
