# Generated by Codex on 2026-05-24

import django.db.models.deletion
from django.db import migrations, models


def assign_customer_to_existing_sales(apps, schema_editor):
    Customer = apps.get_model("sales", "Customer")
    Sale = apps.get_model("sales", "Sale")

    customer = Customer.objects.filter(is_active=True).order_by("id").first()
    if customer is None:
        customer, _ = Customer.objects.get_or_create(
            document_id="00000000",
            defaults={
                "full_name": "Cliente general",
                "email": "",
                "phone": "900000000",
                "is_active": True,
            },
        )

    Sale.objects.filter(customer__isnull=True).update(customer=customer)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_customer_document_email_constraints"),
    ]

    operations = [
        migrations.RunPython(assign_customer_to_existing_sales, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="sale",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="sales.customer",
            ),
        ),
    ]
