# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_require_sale_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[("COMPLETED", "Completado"), ("VOIDED", "Anulado")],
                default="COMPLETED",
                max_length=12,
            ),
        ),
    ]
