# Generated by Codex on 2026-05-24

from django.db import migrations, models


def fill_required_customer_contact_fields(apps, schema_editor):
    Customer = apps.get_model("sales", "Customer")
    used_documents = set(
        Customer.objects.exclude(document_id="").values_list("document_id", flat=True)
    )

    next_document = 1
    for customer in Customer.objects.order_by("id"):
        update_fields = []

        if not customer.document_id:
            while True:
                candidate = f"{next_document:08d}"
                next_document += 1
                if candidate not in used_documents:
                    break
            customer.document_id = candidate
            used_documents.add(candidate)
            update_fields.append("document_id")

        if not customer.phone:
            customer.phone = "900000000"
            update_fields.append("phone")

        if update_fields:
            customer.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_sale_status"),
    ]

    operations = [
        migrations.RunPython(
            fill_required_customer_contact_fields,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                check=~models.Q(("document_id", "")),
                name="customer_document_id_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                check=~models.Q(("phone", "")),
                name="customer_phone_required",
            ),
        ),
    ]
